#pragma once

const double VARIATION_RANGE = 0.2;

const double BASE_C = 30611;
const double C_UPPER = BASE_C+(BASE_C*VARIATION_RANGE);
const double C_LOWER = BASE_C-(BASE_C*VARIATION_RANGE);

const double BASE_D = 113.064;
const double D_UPPER = BASE_D+(BASE_D*VARIATION_RANGE);
const double D_LOWER = BASE_D-(BASE_D*VARIATION_RANGE);

const double BASE_H = 0.5289;
const double H_UPPER = BASE_H+(BASE_H*VARIATION_RANGE);
const double H_LOWER = BASE_H-(BASE_H*VARIATION_RANGE);

const double BASE_BETA =  0.0426;
const double BETA_LOWER = BASE_BETA+(BASE_BETA*VARIATION_RANGE);
const double BETA_UPPER = BASE_BETA-(BASE_BETA*VARIATION_RANGE);

const double BASE_N = 0.5916;
const double N_UPPER = BASE_N+(BASE_N*VARIATION_RANGE);
const double N_LOWER = BASE_N-(BASE_N*VARIATION_RANGE);

const double BASE_LAMBDA_2 = 1.3484;
const double LAMBDA_2_UPPER = BASE_LAMBDA_2+(BASE_LAMBDA_2*VARIATION_RANGE);
const double LAMBDA_2_LOWER = BASE_LAMBDA_2-(BASE_LAMBDA_2*VARIATION_RANGE);

const double BASE_B = 80.5297;
const double B_UPPER = BASE_B+(BASE_B*VARIATION_RANGE);
const double B_LOWER = BASE_B-(BASE_B*VARIATION_RANGE);

const double BASE_R = 2.85;
const double R_UPPER = BASE_R+(BASE_R*VARIATION_RANGE);
const double R_LOWER = BASE_R-(BASE_R*VARIATION_RANGE);

const double BASE_S = 2.25;
const double S_UPPER = BASE_S+(BASE_S*VARIATION_RANGE);
const double S_LOWER = BASE_S-(BASE_S*VARIATION_RANGE);

const double BASE_LAMBDA_1 = 2.9699;
const double LAMBDA_1_UPPER = BASE_LAMBDA_1+(BASE_LAMBDA_1*VARIATION_RANGE);
const double LAMBDA_1_LOWER = BASE_LAMBDA_1-(BASE_LAMBDA_1*VARIATION_RANGE);

const double BASE_A = 1017.1;
const double A_UPPER = BASE_A+(BASE_A*VARIATION_RANGE);
const double A_LOWER = BASE_A-(BASE_A*VARIATION_RANGE);
